# Generated by Django 6.1.1 on 2026-09-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name_en", models.CharField(max_length=100)),
                ("name_fa", models.CharField(max_length=100)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("CRYPTO", "Cryptocurrency"),
                            ("COMMODITY", "Commodity"),
                            ("FOREX", "Forex / Currency"),
                        ],
                        default="CRYPTO",
                        max_length=20,
                    ),
                ),
                (
                    "base_price_usd",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_usd", models.DecimalField(decimal_places=4, max_digits=18)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="dashboard.asset",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AssetPrice",
        ),
    ]
